osx_image: xcode8.3
language: go
go:
  - 1.7

branches:
  only:
  - source

before_install:
  - brew update
  - brew install hugo
  
before_script:
- git config --global user.name 'Travis CI on behalf of Konstantin Pavlov'
- git config --global user.email 'git@konstantinpavlov.net'

script:
  - ./deploy.sh
