branches:
  only:
  - source

before_script:
  - wget https://github.com/spf13/hugo/releases/download/v0.25/hugo_0.25_Linux-32bit.tar.gz
  - tar -zxvf hugo_0.25_Linux-32bit.tar.gz
  - export PATH=$PATH:$PWD/
  - git config --global user.name 'Travis CI on behalf of Konstantin Pavlov'
  - git config --global user.email 'git@konstantinpavlov.net'

script:
  - ./deploy.sh
