language: go
go:
  - 1.7

branches:
  only:
  - source

before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19_i386.deb
  - sudo dpkg -i hugo_0.19_i386.deb

before_script:
- git config --global user.name 'Travis CI on behalf of Konstantin Pavlov'
- git config --global user.email 'git@konstantinpavlov.net'

script:
  - ./deploy.sh
